let mongoose = require('mongoose');
let FlipSchema=mongoose.Schema({
    ARV:{
        type:Number
    },
    FlipperProfit:{
        type:Number
    },
    HoldTime:{
        type:Number
    },
    RepairCosts:{
        type:Number
    },
    Realtor:{
        type:Number
    },
    RealtorAmount:{
        type:Number
    },
    ClosingCost:{
        type:Number
    },
    ClosingAmount:{
        type:Number
    },
    Taxes:{
        type:Number
    },
    TaxesAmount:{
        type:Number
    },
    MonthlyHQA:{
        type:Number
    },
    MonthlyAmount:{
        type:Number
    },
    TotalPropertyCosts:{
        type:Number
    },
    LoanAmount:{
        type:Number
    },
    InterestRate:{
        type:Number
    },
    TotalInterest:{
        type:Number
    },
    Points:{
        type:Number
    },
    PointsAmount:{
        type:Number
    },
    TotalMoneyCost:{
        type:Number
    },
    Wholesale:{
        type:Number
    },
    TotalCosts:{
        type:Number
    },
    MaxFlipperOffer:{
        type:Number
    },
    WholesalePrice:{
        type:Number
    }
    
})

module.exports=FlipSchema;