const mongoose=require('mongoose')
const SqftSchema=mongoose.Schema({
    DeckCost:{
        type:Number
    },
    DeckSqft:{
        type:Number
    },
    DeckTotal:{
        type:Number
    },
    FlooringCost:{
        type:Number
    },
    FlooringSqft:{
        type:Number
    },
    FlooringTotal:{
        type:Number
    },
    InteriorCost:{
        type:Number
    },
    InteriorSqft:{
        type:Number
    },
    InteriorTotal:{
        type:Number
    },
    ExteriorCost:{
        type:Number
    },
    ExteriorSqft:{
        type:Number
    },
    ExteriorTotal:{
        type:Number
    },
    TotalCost:{
        type:Number
    },date:{
        type:Date,
        default:Date.now
    }
})
module.exports=SqftSchema;